In [1]:
import numpy as np
from sklearn import datasets

In [2]:
boston = datasets.load_boston()
X = boston.data
y = boston.target

X = X[y < 50.0]
y = y[y < 50.0]

In [3]:
from c2_model_selection import train_test_split

X_train, y_train, X_test, y_test = train_test_split(X, y, seed=666)

In [4]:
from c8_LinearRegression import LinearRegression

In [5]:
lin_reg1 = LinearRegression()
%time lin_reg1.fit_normal(X_train, y_train)
lin_reg1.score(X_test, y_test)

Wall time: 115 ms


0.8129802602658509

## 使用梯度下降法

In [7]:
lin_reg2 = LinearRegression()
lin_reg2.fit_gd(X_train, y_train)

C:\Users\fangyang\Anaconda3\lib\site-packages\numpy\core\_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
E:\Python project in E\practice\AI_Mechine_Learning入门_Muke\c8_LinearRegression.py:46: RuntimeWarning: overflow encountered in square
  return np.sum((y - X_b.dot(theta)) ** 2) / len(X_b)
E:\Python project in E\practice\AI_Mechine_Learning入门_Muke\c8_LinearRegression.py:70: RuntimeWarning: invalid value encountered in double_scalars
  if (abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon):


LinearRegression()

In [9]:
# 由于数据没有归一化, 导致 n 学习率学出来太大了, 所以上面fit的时候overflow报错
X_train[:2,:]

array([[ 14.2362 ,   0.     ,  18.1    ,   0.     ,   0.693  ,   6.343  ,
        100.     ,   1.5741 ,  24.     , 666.     ,  20.2    , 396.9    ,
         20.32   ],
       [  3.67822,   0.     ,  18.1    ,   0.     ,   0.77   ,   5.362  ,
         96.2    ,   2.1036 ,  24.     , 666.     ,  20.2    , 380.79   ,
         10.19   ]])

In [8]:
# 系数也都没训练出来
lin_reg2.coef_

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [10]:
# 把学习率降低, 就不报错了
lin_reg2.fit_gd(X_train, y_train, eta=0.000001)

LinearRegression()

In [11]:
# 但是问题是模型准确度降低了
lin_reg2.score(X_test, y_test)

0.27556634853389206

In [12]:
# 再在上面的基础上改进, 我们把迭代次数升高100倍
%time lin_reg2.fit_gd(X_train, y_train, eta=0.000001, n_iters=1e6)

Wall time: 1min 43s


LinearRegression()

In [13]:
# 准确度上来了
lin_reg2.score(X_test, y_test)

0.7541852353980765

## 所以在使用梯度下降法之前必须进行数据归一化

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
standard_scaler = StandardScaler()
standard_scaler.fit(X_train, y_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [16]:
X_train_standard = standard_scaler.transform(X_train)

In [17]:
lin_reg3 = LinearRegression()
%time lin_reg3.fit_gd(X_train_standard, y_train)

Wall time: 513 ms


LinearRegression()

In [18]:
# 这样就又快 有准了
X_test_standard = standard_scaler.transform(X_test)
lin_reg3.score(X_test_standard, y_test)

0.8129880620122235

# 梯度下降法的优势

In [23]:
m = 1000  # 1000个样本
n = 5000  # 5000个特征

big_X = np.random.normal(size=(m,n))
true_theta = np.random.uniform(0.0, 100.0, size=n+1)
big_y = big_X.dot(true_theta[1:]) + true_theta[0] + np.random.normal(0., 10., size=m)

In [24]:
big_reg1 = LinearRegression()
%time big_reg1.fit_normal(big_X, big_y)
# 耗时20s, 特征太多了, 求矩阵逆的时候比较费时间

Wall time: 20 s


LinearRegression()

In [26]:
big_reg2 = LinearRegression()
%time big_reg2.fit_gd(big_X, big_y)
# 耗时4.48s , 但是现在我们计算梯度的时候, 
# 需要让1000个样本都来参与计算, 所以当样本量大的时候, 慢
# 改进方法是 随机梯度下降法 , 下节介绍

Wall time: 4.59 s


LinearRegression()

### 小实验

In [19]:
s_X = np.random.normal(size=(2,3))
s_X

array([[0.13735868, 0.15282392, 0.44989519],
       [1.19834187, 0.82447427, 0.55009816]])

In [20]:
t_t = np.random.uniform(0, 100, size=4)
t_t

array([16.12078023, 49.54331668, 33.10436362, 85.39186083])

In [22]:
s_X.dot(t_t[1:])+t_t[0]

array([ 66.40251043, 149.75821236])